# Copyright 2026-present Gian <crow.db@outlook.com>
# Licensed under the Apache License, Version 2.0.
# Use the v2 format explicitly; channel package defaults may still use v1.
unqualified-search-registries = ["docker.io"]
