// Copyright 2026-present buzzcrow <buzzcrow@126.com>
// Licensed under the Apache License, Version 2.0.

fn main() {
    let proto_dir = "src/proto";

    let protos = [
        "src/proto/error_code.proto",
        "src/proto/common_type.proto",
        "src/proto/sysdata_type.proto",
        "src/proto/diskdb_type.proto",
        "src/proto/diskdb_op.proto",
        "src/proto/diskdb_service.proto",
        "src/proto/chunkdb_type.proto",
        "src/proto/chunkdb_op.proto",
        "src/proto/chunkdb_service.proto",
        "src/proto/diskio_op.proto",
        "src/proto/diskio_service.proto",
    ];

    tonic_build::configure()
        .type_attribute(".", "#[allow(clippy::must_use_candidate)]")
        // Add serde + Eq + Hash to message types that internal Rust
        // types embed (for bincode/JSON serialization of records and
        // group-0 sysdata). Debug is already generated by prost::Message.
        .type_attribute(
            "DiskId",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "ChunkId",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "Segment",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        // Value types (serde for bincode/JSON storage).
        .type_attribute("ZoneValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "BusyBlockValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "FreeBlockValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("DiskValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "DiskGroupValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        // Query response types (key + value fields flattened).
        .type_attribute("DiskInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskGroupInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ZoneUsage", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("RackInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("NodeInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Common sysdata value types (serde for bincode/JSON storage).
        .type_attribute("RackValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("NodeValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Group-0 sysdata value types (serde for JSON storage in group 0).
        .type_attribute("StoreValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("GroupValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ReplicaValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("InstanceValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("OwnerMapValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("BindMapValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ServiceExtra", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskdbExtra", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "DiskGroupUsageSummary",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("KvServerExtra", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("HostedGroup", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Enums.
        .type_attribute("HwStatus", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskType", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "ZoneAllocationState",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("BlockState", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ErrorCode", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Recovery scan progress (bincode storage on data groups).
        .type_attribute(
            "RecoveryScanProgressValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "RecoveryScanStatus",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        // chunkdb enums.
        .type_attribute("ECState", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ChunkState", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("StripType", "#[derive(serde::Serialize, serde::Deserialize)]")
        // chunkdb message types — serde for MirrorStrip and EcStrip
        // (flat message types). ChunkStrip and Chunk contain a oneof
        // (Strip) which prost nests in a submodule; serde on the
        // container requires serde on the nested oneof enum, which
        // prost-build's type_attribute cannot target reliably. These
        // are RPC response types, not bincode storage types, so serde
        // is not needed on them now.
        .type_attribute("MirrorStrip", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("EcStrip", "#[derive(serde::Serialize, serde::Deserialize)]")
        .compile_protos(&protos, &[proto_dir])
        .expect("failed to compile CROW protos");
}
