// Copyright 2026-present buzzcrow <buzzcrow@126.com>
// Licensed under the Apache License, Version 2.0.

use std::path::PathBuf;
use std::process::Command;

#[allow(clippy::too_many_lines)]
fn main() {
    let proto_dir = "src/proto";

    // ── Flatbuffer schemas (.fbs) → Rust via flatc ──
    // Common control-message schemas for the crow-rpc library (R104). The
    // `.fbs` files live under `src/fbs/` (separate from `src/proto/` which
    // holds protobuf `.proto` files). `common_msg.fbs` includes
    // `ret_code.fbs` and references FBRetCode in accessors, so it is
    // generated with `--gen-all` to inline ret_code into one self-contained
    // file (avoids flatc's cross-file `crate::` glob quirk). The other two
    // are standalone (no includes used).
    let fbs_files = [
        "src/fbs/ret_code.fbs",
        "src/fbs/msg_type.fbs",
        "src/fbs/common_type.fbs",
        "src/fbs/common_msg.fbs",
    ];
    for f in &fbs_files {
        println!("cargo:rerun-if-changed={f}");
    }
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let flatc = find_flatc();
    // msg_type and common_type: standalone, no cross-file references.
    let status = Command::new(&flatc)
        .arg("--rust")
        .arg("-o")
        .arg(&out_dir)
        .arg("src/fbs/msg_type.fbs")
        .arg("src/fbs/common_type.fbs")
        .status()
        .unwrap_or_else(|e| panic!("failed to run flatc at {}: {e}", flatc.display()));
    assert!(
        status.success(),
        "flatc --rust failed for crow-protocol .fbs schemas"
    );
    // common_msg: --gen-all inlines ret_code.fbs so FBRetCode resolves.
    let status = Command::new(&flatc)
        .arg("--rust")
        .arg("--gen-all")
        .arg("-o")
        .arg(&out_dir)
        .arg("src/fbs/common_msg.fbs")
        .status()
        .unwrap_or_else(|e| panic!("failed to run flatc at {}: {e}", flatc.display()));
    assert!(
        status.success(),
        "flatc --rust --gen-all failed for common_msg.fbs"
    );

    let protos = [
        "src/proto/error_code.proto",
        "src/proto/common_type.proto",
        "src/proto/sysdata_type.proto",
        "src/proto/diskdb_type.proto",
        "src/proto/diskdb_op.proto",
        "src/proto/diskdb_service.proto",
        "src/proto/chunkdb_type.proto",
        "src/proto/chunkdb_op.proto",
        "src/proto/chunkdb_service.proto",
        "src/proto/diskio_op.proto",
        "src/proto/diskio_service.proto",
    ];

    tonic_build::configure()
        .type_attribute(".", "#[allow(clippy::must_use_candidate)]")
        // Add serde + Eq + Hash to message types that internal Rust
        // types embed (for bincode/JSON serialization of records and
        // group-0 sysdata). Debug is already generated by prost::Message.
        .type_attribute(
            "DiskId",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "ChunkId",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "Segment",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        // Value types (serde for bincode/JSON storage).
        .type_attribute("ZoneValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "BusyBlockValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "FreeBlockValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("DiskValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "DiskGroupValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        // Query response types (key + value fields flattened).
        .type_attribute("DiskInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskGroupInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ZoneUsage", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("RackInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("NodeInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Common sysdata value types (serde for bincode/JSON storage).
        .type_attribute("RackValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("NodeValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Group-0 sysdata value types (serde for JSON storage in group 0).
        .type_attribute("StoreValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("GroupValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ReplicaValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("InstanceValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("OwnerMapValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("BindMapValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ServiceExtra", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskdbExtra", "#[derive(serde::Serialize, serde::Deserialize)]")
        // chunkdb range binding sysdata types (serde for JSON storage in group 0).
        .type_attribute(
            "ChunkdbRangeBindingValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "ChunkdbRangeMigrationValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("RangeStatus", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "ChunkdbMigrationState",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "NotMyRangeHint",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "DiskGroupUsageSummary",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("KvServerExtra", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("HostedGroup", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Enums.
        .type_attribute("HwStatus", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskType", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "ZoneAllocationState",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("BlockState", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("CommitState", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ErrorCode", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Recovery scan progress (bincode storage on data groups).
        .type_attribute(
            "RecoveryScanProgressValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "RecoveryScanStatus",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        // chunkdb enums.
        .type_attribute("ECState", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ChunkState", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("StripType", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ChunkType", "#[derive(serde::Serialize, serde::Deserialize)]")
        // chunkdb message types — serde for MirrorStrip and EcStrip
        // (flat message types). ChunkStrip and Chunk contain a oneof
        // (Strip) which prost nests in a submodule; serde on the
        // container requires serde on the nested oneof enum, which
        // prost-build's type_attribute cannot target reliably. These
        // are RPC response types, not bincode storage types, so serde
        // is not needed on them now.
        .type_attribute("MirrorStrip", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("EcStrip", "#[derive(serde::Serialize, serde::Deserialize)]")
        .compile_protos(&protos, &[proto_dir])
        .expect("failed to compile CROW protos");
}

/// Locate the `flatc` schema compiler. Pixi puts it in `$CONDA_PREFIX/bin`;
/// fall back to a pixi env dir relative to the manifest, then to `PATH`.
fn find_flatc() -> PathBuf {
    if let Ok(prefix) = std::env::var("CONDA_PREFIX") {
        let p = PathBuf::from(prefix).join("bin").join("flatc");
        if p.is_file() {
            return p;
        }
    }
    if let Ok(manifest) = std::env::var("CARGO_MANIFEST_DIR") {
        let pixi_env = PathBuf::from(manifest)
            .parent()
            .and_then(|p| p.parent())
            .map(|root| {
                root.join(".pixi")
                    .join("envs")
                    .join("default")
                    .join("bin")
                    .join("flatc")
            });
        if let Some(p) = pixi_env.filter(|p| p.is_file()) {
            return p;
        }
    }
    // Last resort: assume it is on PATH.
    PathBuf::from("flatc")
}
